### PR TITLE
roa_pg

### PR DESCRIPTION
**Pull request by goldenMetteyya**
Expose Chrono and UUID support

### CODE REVIEW

**Comment by Hexilee** [comment]
I prefer optional features like:

```toml
[features]
with-bit-vec-0_6 = ["tokio-postgres/with-bit-vec-0_6"]
with-chrono-0_4 = ["tokio-postgres/with-chrono-0_4"]
with-eui48-0_4 = ["tokio-postgres/with-eui48-0_4"]
with-geo-types-0_4 = ["tokio-postgres/with-geo-types-0_4"]
with-serde_json-1 = ["tokio-postgres/with-serde_json-1"]
with-uuid-0_8 = ["tokio-postgres/with-uuid-0_8"]
with-time-0_2 = ["tokio-postgres/with-time-0_2"]
```

**Comment by goldenMetteyya** [comment]
> I prefer optional features like:
> 
> ```toml
> [features]
> with-bit-vec-0_6 = ["tokio-postgres/with-bit-vec-0_6"]
> with-chrono-0_4 = ["tokio-postgres/with-chrono-0_4"]
> with-eui48-0_4 = ["tokio-postgres/with-eui48-0_4"]
> with-geo-types-0_4 = ["tokio-postgres/with-geo-types-0_4"]
> with-serde_json-1 = ["tokio-postgres/with-serde_json-1"]
> with-uuid-0_8 = ["tokio-postgres/with-uuid-0_8"]
> with-time-0_2 = ["tokio-postgres/with-time-0_2"]
> ```

sounds good

**Comment by goldenMetteyya** [comment]
I have reflected that change in the pr

**Comment by Hexilee** [comment]
"default-features = false" is required because we don't need feature "runtime"

**Comment by goldenMetteyya** [comment]
> "default-features = false" is required because we don't need feature "runtime"

ok understood, reflected

**Comment by goldenMetteyya** [comment]
I also bumped the version to 0.5.1

**Pull request merged**
